spring:
  application:
    name: spring-cloud-eureka-service
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      # 设置与Eureka Server交互的地址, 多个地址可使用','分隔。
      defaultZone: http://eurekaservice01:8761
  instance:
    hostname: eurekaservice02
