spring:
  application:
    name: spring-cloud-eureka-service
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    # 是否当作客户端注册到服务端, 默认为true
    register-with-eureka: false
    # 是否从Eureka获取注册信息
    fetch-registry: false
    serviceUrl:
      # 设置与Eureka Server交互的地址, 多个地址可使用','分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
